"use client"

export {
  getWebApp,
  isInTelegram,
  isVersionAtLeast,
  getRawUserData,
  getUserDisplayName,
  getUserIdentifier,
  getUserAvatarUrl,
  getUserInfoWithAvatar,
  openExternalLink,
  openTelegramLink,
  openInvoice,
  switchInlineQuery,
  hideKeyboard,
  haptic,
  cloudStorage,
  deviceStorage,
  secureStorage,
  dialog,
  readClipboard,
  scanQr,
  shareToStory,
  shareMessage,
  setEmojiStatus,
  requestEmojiStatusAccess,
  downloadFile,
  requestWriteAccess,
  requestContact,
  requestChat,
  biometric,
  location,
} from '@mr-m/tg-kit'

export {
  useTelegramWebApp,
  useTelegramUser,
  useTelegramStartParam,
  useTelegramEvent,
  useTelegramBackButton,
  useTelegramMainButton,
  useTelegramSecondaryButton,
  useTelegramSettingsButton,
  useHapticFeedback,
  useTelegramTheme,
  useTelegramViewport,
  useTelegramFullscreen,
  useOrientationLock,
  useSafeArea,
  useIsActive,
  useCloudStorage,
  useDeviceStorage,
  useSecureStorage,
  useAccelerometer,
  useGyroscope,
  useDeviceOrientation,
  useBiometric,
  useLocation,
  useHomeScreen,
  useShareToStory,
  useShareMessage,
  useSetEmojiStatus,
  useRequestEmojiStatusAccess,
  useDownloadFile,
  useRequestWriteAccess,
  useRequestContact,
  useSwitchInlineQuery,
  useRequestChat,
  useHideKeyboard,
} from '@mr-m/tg-kit'

export {
  TelegramProvider,
  useTelegram,
  FullscreenProvider,
  useFullscreen,
} from '@mr-m/tg-kit'

export type {
  TgUser,
  TgWebApp,
  TelegramContextValue,
  TelegramProviderOptions,
  FullscreenProviderOptions,
  DownloadFileParams,
  EmojiStatusParams,
  StoryShareParams,
  LocationData,
  PopupParams,
  RequestChatParams,
  SafeAreaInset,
  WebAppEventType,
} from '@mr-m/tg-kit'

export {
  loadTelegramScript,
  getTelegramCdnUrl,
  injectTelegramScriptTag,
} from '@mr-m/tg-kit/cdn'

export {
  isDevMode,
  installDevMode,
  createMockWebApp,
} from '@mr-m/tg-kit/dev'
