export {
  getWebApp,
  isInTelegram,
  isVersionAtLeast,
  getRawUserData,
  getUserDisplayName,
  getUserIdentifier,
  getUserAvatarUrl,
  getUserInfoWithAvatar,
  openExternalLink,
  openTelegramLink,
  openInvoice,
  switchInlineQuery,
  hideKeyboard,
  haptic,
  cloudStorage,
  deviceStorage,
  secureStorage,
  dialog,
  readClipboard,
  scanQr,
  shareToStory,
  shareMessage,
  setEmojiStatus,
  requestEmojiStatusAccess,
  downloadFile,
  requestWriteAccess,
  requestContact,
  requestChat,
  biometric,
  location,
} from './core';

export {
  loadTelegramScript,
  getTelegramCdnUrl,
  injectTelegramScriptTag,
} from './cdn';

export {
  createMockWebApp,
  installDevMode,
  isDevMode,
} from './dev';

export type {
  TgUser,
  TgWebApp,
  TgThemeParams,
  WebAppInitData,
  WebAppEventType,
  TgPlatform,
  BottomButton,
  BackButton,
  HapticFeedback,
  CloudStorage,
  DeviceStorage,
  SecureStorage,
  SafeAreaInset,
  PopupParams,
  LocationData,
  RequestChatParams,
  DownloadFileParams,
  EmojiStatusParams,
  StoryShareParams,
} from './types/webapp';
